// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIOYPrXGkotH9x-1aFkdldoVQC15CSzCE',
    appId: '1:883895005810:web:1a2232e576a5a705f4c8eb',
    messagingSenderId: '883895005810',
    projectId: 'to-do-app-7137d',
    authDomain: 'to-do-app-7137d.firebaseapp.com',
    storageBucket: 'to-do-app-7137d.appspot.com',
    measurementId: 'G-LDMF1W2W9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqChOU5W5b-uYt1C9EU1teItH8tVmTlcc',
    appId: '1:883895005810:android:3c40520c846057eaf4c8eb',
    messagingSenderId: '883895005810',
    projectId: 'to-do-app-7137d',
    storageBucket: 'to-do-app-7137d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq4Z8telWaMevlXPFwRjPlDF4WImhQ04M',
    appId: '1:883895005810:ios:98b2b2ffed3a6ad3f4c8eb',
    messagingSenderId: '883895005810',
    projectId: 'to-do-app-7137d',
    storageBucket: 'to-do-app-7137d.appspot.com',
    iosBundleId: 'com.example.todoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq4Z8telWaMevlXPFwRjPlDF4WImhQ04M',
    appId: '1:883895005810:ios:df7a4b46983a7141f4c8eb',
    messagingSenderId: '883895005810',
    projectId: 'to-do-app-7137d',
    storageBucket: 'to-do-app-7137d.appspot.com',
    iosBundleId: 'com.example.todoApplication.RunnerTests',
  );
}
